-- CREATE USER
CREATE TABLE WB_USER
    (ID NUMERIC,
     NAME VARCHAR(255),
     CONSTRAINT WB_USER_PK PRIMARY KEY (ID));

-- CREATE SKILLS
CREATE TABLE WB_SKILLS
    (ID NUMERIC,
     NAME VARCHAR(255),
     CONSTRAINT WB_SKILLS_PK PRIMARY KEY (ID));

-- CREATE TRAITS
CREATE TABLE WB_TRAITS
    (ID NUMERIC,
     NAME VARCHAR(255),
     CONSTRAINT WB_TRAITS_PK PRIMARY KEY (ID));

-- CREATE ITEMS
CREATE TABLE WB_ITEMS
    (ID NUMERIC,
     NAME VARCHAR(255),
     CONSTRAINT WB_ITEMS_PK PRIMARY KEY (ID));

-- CREATE CHARACTERS
CREATE TABLE WB_CHARACTERS
    (ID NUMERIC,
     NAME VARCHAR(255),
     CONSTRAINT WB_CHARACTERS_PK PRIMARY KEY (ID));

ALTER TABLE WB_CHARACTERS
    ADD CONSTRAINT FK_CHARACTER_USER
    FOREIGN KEY (USER)
    REFERENCES WB_USER (ID);